### ISSUE TITLE
IPv4 addressing

### ISSUE THREAD

**Issue by Anjalikamath** [Crio-Bytes/Networking#11]
* MicroByte Title: IPv4 addressing

* Domain: Networking

* Scope of learning for learners:
Learning about classfull and classless IP addressing

* Activities:
Conversion from dotted decimal format to binary and vice-versa, finding network mask,identifying different classes of IP addresses etc

**Comment by YourAKShaw** [comment]
Kindly use bullet points. Makes it more readable.
