### ISSUE TITLE
Peer to Peer File sharing

### ISSUE THREAD

**Issue by sainimohit23** [Crio-Bytes/Networking#3]
**MicroByte Title:** Peer to Peer File sharing

**Domain:**
* Networking
* Torrent.

**Scope of learning for learners:** 
* BitTorrent Networking Protocol
* Peer to Peer Network architecture
* Advantage of the one over other.

**Activities:**
* Getting information like IP address, data exchange rate, peer torrent client from a torrent tracker.

**Comment by sainimohit23** [comment]
Please assign me this.

**Comment by amoghrajesh** [comment]
Sure @sainimohit23 you can start working on this.
Keep in mind the structure we expect in the MicroByte and the learning by doing methodology. Do not give out direct tutorial experience. 
All the best!

Also, kindly make each comma-separated value as a point under Scope and Activities :)
